package com.company.loaf.routinescheduler;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ProgressBar;
import android.widget.Spinner;
import android.widget.TextView;


public class MainActivity extends AppCompatActivity implements MainView, AdapterView.OnItemSelectedListener{

    private TextView mErrorText, mResultText;
    private ProgressBar mProgressBar;
    private EditText mInterval, mDaysAgo;
    private Spinner mYearSpinner, mMonthSpinner, mDaySpinner;
    private MainPresenter mPresenter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mErrorText = findViewById(R.id.error_text);
        mResultText = findViewById(R.id.result_text);
        mInterval = findViewById(R.id.interval_input);
        mDaysAgo = findViewById(R.id.days_ago_input);
        mYearSpinner = findViewById(R.id.year_spinner);
        mMonthSpinner = findViewById(R.id.month_spinner);
        mDaySpinner = findViewById(R.id.day_spinner);

        findViewById(R.id.submit_button).setOnClickListener(v -> validateInfo());

        mPresenter = new MainPresenter(this, new MainInteractor());

        generateYears();
        generateMonths();
        generateDays();

        mYearSpinner.setOnItemSelectedListener(this);
        mMonthSpinner.setOnItemSelectedListener(this);

    }

    @Override
    protected void onDestroy() {
        mPresenter.onDestroy();
        super.onDestroy();
    }

    @Override
    public void showError() {
        mErrorText.setVisibility(View.VISIBLE);
    }

    @Override
    public void hideError() {
        mErrorText.setVisibility(View.INVISIBLE);
    }

    @Override
    public void showProgress() {

    }

    @Override
    public void hideProgress() {

    }

    @Override
    public void displayInfo(String info) {
        mResultText.setText(info);
    }

    @Override
    public void validateInfo() {
        mPresenter.validateInfo(mInterval.getText().toString(), mDaysAgo.getText().toString());
    }


    //Not sure exactly where the 'generate' functions should be
    //Since it requires 'context' I assume that it is best to leave it in the view as the actual data is generated by the interactor (arrays)
    @Override
    public void generateYears() {
        ArrayAdapter adapter = new ArrayAdapter<String>(this, android.R.layout.simple_spinner_item,  mPresenter.generateYears());
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        mYearSpinner.setAdapter(adapter);
    }

    @Override
    public void generateDays() {
        ArrayAdapter adapter = new ArrayAdapter<String>(this, android.R.layout.simple_spinner_item,  mPresenter.generateDays(mMonthSpinner.getSelectedItem().toString(), mYearSpinner.getSelectedItem().toString()));
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        mDaySpinner.setAdapter(adapter);
    }

    @Override
    public void generateMonths() {
        ArrayAdapter<CharSequence> adapter = ArrayAdapter.createFromResource(this, R.array.months_array, android.R.layout.simple_spinner_item);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        mMonthSpinner.setAdapter(adapter);
    }

    @Override
    public void onItemSelected(AdapterView<?> adapterView, View view, int i, long l) {
        generateDays();
    }

    @Override
    public void onNothingSelected(AdapterView<?> adapterView) {
        generateDays();
    }
}
